CREATE TABLE BOOKS (
	ID int NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRICE  date NOT NULL,
	CATEGORYID date NOT NULL,
	AUTHORID date NOT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE CATEGORIES (
	ID INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID, NAME)
);
CREATE TABLE AUTHORS (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY(ID, NAME)
	
);

INSERT INTO CATEGORIES(ID, NAME)
VALUES
	(1, 'Cat-A'),
	(2, 'Cat-B'),
	(3, 'Cat-C'),
	(7, 'Cat-D'),
	(8, 'Cat-E'),
	(4, 'Cat-F'),
	(10, 'Cat-G'),
	(12, 'Cat-H'),
	(6, 'Cat-I');
INSERT INTO
	AUTHORS
VALUES
	(1, 'Author-A'),
	(2, 'Author-B'),
	(3, 'Author-C'),
	(10, 'Author-D'),
	(12, 'Author-E');
INSERT INTO BOOKS (ID, NAME, CATEGORYID, AUTHORID)
VALUES
	(1, 'ok-A', 100, 1, 2),
	(2, 'Book-B', 200, 2, 2),
	(3,' Book-C', 150, 3, 2),
	(4, 'Book-D', 100, 3, 1),
	(5, 'Book-E', 200, 3, 1),
	(6, 'Book-F', 150, 4, 1),
	(7, 'Book-G', 100, 5, 5),
	(8, 'Book-H', 200, 5, 6),
	(9, 'Book-I', 150, 7, 8);
	
SELECT * FROM BOOKS.NAME INNER JOIN CATEGORIES.NAME
ON AUTHORS.NAME = CATEGPRIES.NAME

SELECT C.NAME AS Categoria, B.NAME AS Libro
FROM CATEGORIES C
RIGHT JOIN BOOKS B ON C.ID = B.CATEGORYID;

SELECT B.NAME AS Libro, C.NAME AS Categoria
FROM BOOKS B
LEFT JOIN CATEGORIES C ON B.CATEGORYID = C.ID;

SELECT *
FROM BOOKS
NATURAL JOIN AUTHORS;

SELECT B.NAME AS Libro, B.CATEGORYID
FROM BOOKS B
LEFT JOIN CATEGORIES C ON B.CATEGORYID = C.ID
WHERE C.ID IS NULL; 

SELECT A.NAME AS Autor
FROM BOOKS B
RIGHT JOIN AUTHORS A ON B.AUTHORID = A.ID
WHERE B.ID IS NULL; 

